### ISSUE TITLE
Panic while updating the best block

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1154]
Commit hash : bbf16b0be43bdee3da7aef55bd2721c835a298a0

```
====================

stack backtrace:
   0:     0x55a5da150705 - backtrace::backtrace::libunwind::trace::h361e3a05e9850cda
                        at /home/kodebox/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h019a930391c5a0d7
                        at /home/kodebox/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x55a5da14a62e - backtrace::capture::Backtrace::new_unresolved::h65590a2fb0c352a8
                        at /home/kodebox/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x55a5da14a58c - backtrace::capture::Backtrace::new::h7f7e884b3696657b
                        at /home/kodebox/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x55a5d9121c61 - panic_hook::panic_hook::hb34216610889f64e
                        at util/panic_hook/src/lib.rs:53
   4:     0x55a5d9122887 - core::ops::function::Fn::call::hf29dbb7ace17a398
                        at libcore/ops/function.rs:78
   5:     0x55a5daace013 - std::panicking::rust_panic_with_hook::h86e619a638415243
                        at libstd/panicking.rs:481
   6:     0x55a5da86631f - std::panicking::begin_panic::hc74fa6f45f828c97
                        at libstd/panicking.rs:411
   7:     0x55a5d96ffd00 - codechain_core::blockchain::blockchain::BlockChain::update_best_as_committed::h97284567cd036c56
                        at core/src/blockchain/blockchain.rs:234
   8:     0x55a5d93fdc01 - codechain_core::client::client::Client::update_best_as_committed::ha6fbfefaef99566b
                        at core/src/client/client.rs:234
   9:     0x55a5d94752cd - <codechain_core::service::ClientIoHandler as codechain_io::IoHandler<codechain_core::service::ClientIoMessage>>::message::h68e3c02f2a787f00
                        at core/src/service.rs:122
  10:     0x55a5d967a039 - codechain_io::worker::Worker::do_work::hfebedfe3bb8161b4
                        at /home/kodebox/codechain-for-corgi/util/io/src/worker.rs:142
  11:     0x55a5d967ab56 - codechain_io::worker::Worker::work_loop::hce3f265054104e90
                        at /home/kodebox/codechain-for-corgi/util/io/src/worker.rs:110
  12:     0x55a5d967901d - codechain_io::worker::Worker::new::{{closure}}::h03119eb251ee1a63
                        at /home/kodebox/codechain-for-corgi/util/io/src/worker.rs:84
  13:     0x55a5d9713ab1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd5766481ac5e86ba
                        at libstd/sys_common/backtrace.rs:136
  14:     0x55a5d97048b3 - std::thread::Builder::spawn::{{closure}}::{{closure}}::hd3c3620fabd77563
                        at libstd/thread/mod.rs:409
  15:     0x55a5d974eba3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8830c313a11b2190
                        at libstd/panic.rs:313
  16:     0x55a5d9769b16 - std::panicking::try::do_call::h998b4ae9e063af2c
                        at libstd/panicking.rs:310
  17:     0x55a5daaf7549 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  18:     0x55a5d9769840 - std::panicking::try::h9d567a035f1e90f5
                        at libstd/panicking.rs:289
  19:     0x55a5d974ed13 - std::panic::catch_unwind::h5491e86298d8d488
                        at libstd/panic.rs:392
  20:     0x55a5d97038ac - std::thread::Builder::spawn::{{closure}}::h1c32ce1370919cb5
                        at libstd/thread/mod.rs:408
  21:     0x55a5d9704c51 - <F as alloc::boxed::FnBox<A>>::call_box::hdc9ee972b7519fc0
                        at liballoc/boxed.rs:646
  22:     0x55a5daae689a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hfedf8d10954bca7a
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::h75d887c7d2cc4479
                        at libstd/sys_common/thread.rs:24
  23:     0x55a5daace725 - std::sys::unix::thread::Thread::new::thread_start::h8414caee632bf9ed
                        at libstd/sys/unix/thread.rs:90
  24:     0x7fe9b72e36da - start_thread
  25:     0x7fe9b6df488e - __clone
  26:                0x0 - <unknown>

Thread 'Client Worker #3' panicked at 'assertion failed: block_detail.number <= prev_best_block_detail.number', core/src/blockchain/blockchain.rs:234

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new

```

**Comment by jhs7jhs** [comment]
This is not reproducible. Hard to figure out.

**Comment by sgkim126** [comment]
I think it can be fixed while fixing other Tendermint issues.
Let's close it and reopen if it happens.
