### ISSUE TITLE
Thread 'main' panicked at 'attempt to subtract with overflow', core/src/miner/mem_pool_types.rs:140 `

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1217]
```
====================

stack backtrace:
   0:     0x55b880d373a6 - backtrace::backtrace::libunwind::trace::h6f69f7a8523b3b48
                        at /home/sgkim126/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hfcb48dcb3ac891e8
                        at /home/sgkim126/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x55b880d31953 - backtrace::capture::Backtrace::new_unresolved::h3e5684a38718154b
                        at /home/sgkim126/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x55b880d318ad - backtrace::capture::Backtrace::new::h448ec18ea4124027
                        at /home/sgkim126/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x55b87fc4eddd - panic_hook::panic_hook::ha4aecdc1727731f8
                        at util/panic_hook/src/lib.rs:53
   4:     0x55b87fc4f787 - core::ops::function::Fn::call::h50bcd1f0a1621bec
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:78
   5:     0x55b8816e7189 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   6:     0x55b8816e6c31 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   7:     0x55b8816e6b15 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   8:     0x55b88170278c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   9:     0x55b8817026bb - core::panicking::panic::h6f50c0de2dcd7974
                        at src/libcore/panicking.rs:59
  10:     0x55b87fe6f607 - codechain_core::miner::mem_pool_types::TransactionOrder::for_transaction::h9ab52378e7c34aa7
                        at core/src/miner/mem_pool_types.rs:140
  11:     0x55b87fe47408 - codechain_core::miner::mem_pool::MemPool::recover_from_db::hd6bb2e01853dc084
                        at core/src/miner/mem_pool.rs:448
  12:     0x55b87fe466aa - codechain_core::miner::mem_pool::MemPool::with_limits::hec5edfd4642980cd
                        at core/src/miner/mem_pool.rs:137
  13:     0x55b87fe4adf5 - codechain_core::miner::miner::Miner::new_raw::h0459700fbbc0d627
                        at core/src/miner/miner.rs:154
  14:     0x55b87fe4acd4 - codechain_core::miner::miner::Miner::new::h76cde343f7cad099
                        at core/src/miner/miner.rs:140
  15:     0x55b87fab0923 - codechain::run_node::new_miner::hcc791d16234e6768
                        at codechain/run_node.rs:122
  16:     0x55b87fab3457 - codechain::run_node::run_node::hd9e9009501d05eea
                        at codechain/run_node.rs:258
  17:     0x55b87fb3fe75 - codechain::run::hbaf07a7a2a536376
                        at codechain/main.rs:92
  18:     0x55b87fb3fd53 - codechain::main::hbcaabf6f089bd12b
                        at codechain/main.rs:83
  19:     0x55b87fa3c7f1 - std::rt::lang_start::{{closure}}::h8166b09954d044f5
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  20:     0x55b8816e6ab2 - std::rt::lang_start_internal::{{closure}}::hdfc28107b5be47c9
                        at src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h69790245ac2d03fe
                        at src/libstd/panicking.rs:310
  21:     0x55b8816fbf19 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  22:     0x55b8816e7483 - std::panicking::try::h9c1cbc5599e1efbf
                        at src/libstd/panicking.rs:289
                         - std::panic::catch_unwind::h0562757d03ff60b3
                        at src/libstd/panic.rs:398
                         - std::rt::lang_start_internal::h540c897fe52ba9c5
                        at src/libstd/rt.rs:58
  23:     0x55b87fa3c7b8 - std::rt::lang_start::hcef12e8ed789262a
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  24:     0x55b87fb3ff09 - main
  25:     0x7f23373c2b96 - __libc_start_main
  26:     0x55b87f7ba1a9 - _start
  27:                0x0 - <unknown>

Thread 'main' panicked at 'attempt to subtract with overflow', core/src/miner/mem_pool_types.rs:140
```
It occured when I restarted it several times.

**Comment by HoOngEe** [comment]
When terminated unexpectedly in add function, there is a chance that the item whose sequence is smaller than current sequence but did not properly dropped from `by_hash` in both mempool and backup db. Recovering function operates based on the `by_hash` hashmap. Therefore during the calculation of item.seq() - seq_seq in TransactionOrder::for_transaction function, the program could be panicked at 'attempt to subtract with overflow'.
