### ISSUE TITLE
Panic while restoring mem_pool

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#1232]
Version : df2a74b6c134b7c04cac6a28038c3324dee8f358 + index out of range bug fix

```
====================

stack backtrace:
   0:     0x55f4ea3f6346 - backtrace::backtrace::libunwind::trace::h6f69f7a8523b3b48
                        at /home/majecty/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hfcb48dcb3ac891e8
                        at /home/majecty/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x55f4ea3f08f3 - backtrace::capture::Backtrace::new_unresolved::h3e5684a38718154b
                        at /home/majecty/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x55f4ea3f084d - backtrace::capture::Backtrace::new::h448ec18ea4124027
                        at /home/majecty/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x55f4e930f39d - panic_hook::panic_hook::ha4aecdc1727731f8
                        at util/panic_hook/src/lib.rs:53
   4:     0x55f4e930fd47 - core::ops::function::Fn::call::h50bcd1f0a1621bec
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:78
   5:     0x55f4eadbd759 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   6:     0x55f4eadbd201 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                        at src/libstd/panicking.rs:398
   7:     0x55f4eadbd0e5 - rust_begin_unwind
                        at src/libstd/panicking.rs:325
   8:     0x55f4eadd8d5c - core::panicking::panic_fmt::h4d67173bc68f6d5a
                        at src/libcore/panicking.rs:95
   9:     0x55f4eadd8c8b - core::panicking::panic::h6f50c0de2dcd7974
                        at src/libcore/panicking.rs:59
  10:     0x55f4e952e687 - codechain_core::miner::mem_pool_types::TransactionOrder::for_transaction::h9ab52378e7c34aa7
                        at core/src/miner/mem_pool_types.rs:140
  11:     0x55f4e9506588 - codechain_core::miner::mem_pool::MemPool::recover_from_db::hd6bb2e01853dc084
                        at core/src/miner/mem_pool.rs:448
  12:     0x55f4e950582a - codechain_core::miner::mem_pool::MemPool::with_limits::hec5edfd4642980cd
                        at core/src/miner/mem_pool.rs:137
  13:     0x55f4e9509f75 - codechain_core::miner::miner::Miner::new_raw::h0459700fbbc0d627
                        at core/src/miner/miner.rs:154
  14:     0x55f4e9509e54 - codechain_core::miner::miner::Miner::new::h76cde343f7cad099
                        at core/src/miner/miner.rs:140
  15:     0x55f4e9171043 - codechain::run_node::new_miner::hcc791d16234e6768
                        at codechain/run_node.rs:122
  16:     0x55f4e9173b77 - codechain::run_node::run_node::hd9e9009501d05eea
                        at codechain/run_node.rs:258
  17:     0x55f4e9200435 - codechain::run::hbaf07a7a2a536376
                        at codechain/main.rs:92
  18:     0x55f4e9200313 - codechain::main::hbcaabf6f089bd12b
                        at codechain/main.rs:83
  19:     0x55f4e90fcf11 - std::rt::lang_start::{{closure}}::h8166b09954d044f5
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  20:     0x55f4eadbd082 - std::rt::lang_start_internal::{{closure}}::hdfc28107b5be47c9
                        at src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h69790245ac2d03fe
                        at src/libstd/panicking.rs:310
  21:     0x55f4eadd24e9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  22:     0x55f4eadbda53 - std::panicking::try::h9c1cbc5599e1efbf
                        at src/libstd/panicking.rs:289
                         - std::panic::catch_unwind::h0562757d03ff60b3
                        at src/libstd/panic.rs:398
                         - std::rt::lang_start_internal::h540c897fe52ba9c5
                        at src/libstd/rt.rs:58
  23:     0x55f4e90fced8 - std::rt::lang_start::hcef12e8ed789262a
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  24:     0x55f4e92004c9 - main
  25:     0x7f9bb379bb96 - __libc_start_main
  26:     0x55f4e8e7aba9 - _start
  27:                0x0 - <unknown>

Thread 'main' panicked at 'attempt to subtract with overflow', core/src/miner/mem_pool_types.rs:140

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new

```

**Comment by sgkim126** [comment]
Close because it's duplicated with https://github.com/CodeChain-io/codechain/issues/1217
