### ISSUE TITLE
Tendermint e2e tests failed with assertion failure

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain#1365]
```
  1) Tendermint 
       Block sync:
     Error: An error occurred while chain_getBestBlockNumber: FetchError: request to http://localhost:8336/ failed, reason: connect ECONNREFUSED 127.0.0.1:8336
      at /home/travis/build/CodeChain-io/codechain/test/node_modules/codechain-sdk/lib/rpc/index.js:26:39
      at ClientBrowser._parseResponse (node_modules/jayson/lib/client/browser.js:119:5)
      at /home/travis/build/CodeChain-io/codechain/test/node_modules/jayson/lib/client/browser.js:103:10
      at /home/travis/build/CodeChain-io/codechain/test/node_modules/codechain-sdk/lib/rpc/index.js:52:24
      at process._tickCallback (internal/process/next_tick.js:68:7)
  2) Tendermint 
       "after each" hook for "Block sync":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/CodeChain-io/codechain/test/src/e2e.long/tendermint.test.ts)
```

```
stack backtrace:
   0:     0x55909fc78616 - backtrace::backtrace::libunwind::trace::h9f531b214dad4460
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h82a383a74dfe1e40
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x55909fc72bc3 - backtrace::capture::Backtrace::new_unresolved::h549fb237971be157
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x55909fc72b1d - backtrace::capture::Backtrace::new::h184562695d0b61b2
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x55909eb7449d - panic_hook::panic_hook::hb1270cf531cbf1ba
                        at util/panic_hook/src/lib.rs:53
   4:     0x55909eb75657 - core::ops::function::Fn::call::h3ed71ede80b70ffc
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:78
   5:     0x5590a064b169 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                        at src/libstd/panicking.rs:495
   6:     0x5590a0205377 - std::panicking::begin_panic::ha76b855b94e8bf56
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:425
   7:     0x55909f1fa3f4 - codechain_core::blockchain::blockchain::BlockChain::update_best_as_committed::h98f847c3d5c668e2
                        at core/src/blockchain/blockchain.rs:254
   8:     0x55909f1868d0 - codechain_core::client::client::Client::update_best_as_committed::h50dcab4001067f3b
                        at core/src/client/client.rs:233
   9:     0x55909f0ad08a - <codechain_core::service::ClientIoHandler as codechain_io::IoHandler<codechain_core::service::ClientIoMessage>>::message::h41d41a6ee93dcedd
                        at core/src/service.rs:110
  10:     0x55909f00ccfc - codechain_io::worker::Worker::do_work::he833055c749746d6
                        at /home/travis/build/CodeChain-io/codechain/util/io/src/worker.rs:142
  11:     0x55909f00d83a - codechain_io::worker::Worker::work_loop::hbfcf024f2c42e101
                        at /home/travis/build/CodeChain-io/codechain/util/io/src/worker.rs:110
  12:     0x55909f00b9d2 - codechain_io::worker::Worker::new::{{closure}}::hd809f12818fd0e99
                        at /home/travis/build/CodeChain-io/codechain/util/io/src/worker.rs:84
  13:     0x55909f211ed0 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha2aa98f1513193e6
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/backtrace.rs:136
  14:     0x55909efbdf02 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha952d074a01502c0
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:477
  15:     0x55909f0f9312 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc1e348b7806c3ea4
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:319
  16:     0x55909f23b056 - std::panicking::try::do_call::he42e592e33b4d319
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:310
  17:     0x5590a065fab9 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  18:     0x55909f23a83f - std::panicking::try::h281060020d15186b
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
  19:     0x55909f0f94a2 - std::panic::catch_unwind::h7080be8b1c23070c
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
  20:     0x55909efbcafd - std::thread::Builder::spawn_unchecked::{{closure}}::h052cbe0b0a5a66aa
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
  21:     0x55909efbe667 - <F as alloc::boxed::FnBox<A>>::call_box::hf866c89698560ca3
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
  22:     0x5590a065367d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hece536cf07b94f8d
                        at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                         - std::sys_common::thread::start_thread::h9605a7df0f911844
                        at src/libstd/sys_common/thread.rs:24
                         - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                        at src/libstd/sys/unix/thread.rs:90
  23:     0x7fea9bcfa183 - start_thread
  24:     0x7fea9b810ffc - clone
  25:                0x0 - <unknown>

Thread 'Client Worker #3' panicked at 'assertion failed: block_detail.number <= prev_best_block_detail.number', core/src/blockchain/blockchain.rs:254
```
I reran the test, but I cannot reproduce the crash.

**Comment by sgkim126** [comment]
This crash occurred on the current master(https://travis-ci.com/sgkim126/codechain/jobs/183652287) again, but I cannot get log because transfer.sh had downed.

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1375 closed it.
