### ISSUE TITLE
one test case in e2e.long/staking.test.ts fails

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain#1719]
The test case with the name "cannot delegate to non-candidate" usually passes but there is some chance it fails.
I found the [travis log](https://travis-ci.org/CodeChain-io/codechain/jobs/563885161#L1921) saying 
```
1) Staking
       cannot delegate to non-candidate:
     AssertionError: expected null not to be null
      at Context.<anonymous> (src/e2e.long/staking.test.ts:545:49)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by HoOngEe** [comment]
It has not been reproduced in local setting. When it comes into problem again, I'll reopen it.
