### ISSUE TITLE
Managing accounts: import subcommand causes panick

### ISSUE THREAD

**Issue by ScarletBlue** [CodeChain-io/codechain#281]
When trying to import accounts through the account subcommand, the system panics.

``` 
./target/release/codechain account import
```

This command causes this result:

```
====================

stack backtrace:
   0:     0x7fc0e543f2cc - backtrace::backtrace::trace::hbeb2615a98429bf3
   1:     0x7fc0e543dab2 - backtrace::capture::Backtrace::new::h3e73018e10f4aaf0
   2:     0x7fc0e543d02a - panic_hook::panic_hook::hb36f80cc3e603568
   3:     0x7fc0e5a868b9 - std::panicking::rust_panic_with_hook::habacef8c65a3b0d4
                        at libstd/panicking.rs:403
   4:     0x7fc0e5a866a2 - std::panicking::begin_panic_fmt::h20e14b91a98870b3
                        at libstd/panicking.rs:349
   5:     0x7fc0e5a865d2 - rust_begin_unwind
                        at libstd/panicking.rs:325
   6:     0x7fc0e5ad6f30 - core::panicking::panic_fmt::h8a30aa26a6a035a8
                        at libcore/panicking.rs:72
   7:     0x7fc0e5ad6e56 - core::panicking::panic::hebbf35921bdc7e33
                        at libcore/panicking.rs:51
   8:     0x7fc0e53bf885 - codechain::account_command::run_account_command::hfd40acec2a3026c9
   9:     0x7fc0e5421854 - codechain::main::h2a22a16d6c6d5453
  10:     0x7fc0e5424c81 - std::rt::lang_start::{{closure}}::h362c25d7965b210a
  11:     0x7fc0e5a86537 - std::rt::lang_start_internal::{{closure}}::hb3d070a2bac9f126
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hfce3050be9508e94
                        at libstd/panicking.rs:306
  12:     0x7fc0e5a9a61e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  13:     0x7fc0e5a831e5 - std::panicking::try::h181b418ccf9daec0
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::h2e22b8787335a1ba
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h4193b9a4ab9d505a
                        at libstd/rt.rs:58
  14:     0x7fc0e54245d3 - main
  15:     0x7fc0e3e6082f - __libc_start_main
  16:     0x7fc0e534e888 - _start
  17:                0x0 - <unknown>

Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335
```

**Comment by joojis** [comment]
Patch: https://github.com/CodeChain-io/codechain/pull/423
