### ISSUE TITLE
Fix test failure on Travis

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#643]
The test passes on my local environment. I guess it's a flaky test.

```
FAIL src/sync.test.ts (27.745s)
  ● 2 nodes › A-B connected › A-B diverged › It should be synced when nodeA becomes ahead
    expect(received).toEqual(expected)
    Expected value to equal:
      {"value": "c4f2b6e782ad53ae6d7e49357bc4b59376817514e6acbf07616b34d9ade1fdd5"}
    Received:
      {"value": "e981357c06a43edf85bdc005a257253e8e3ea4f22a936284267c1ead247759c9"}
    Difference:
    - Expected
    + Received
      H256 {
    -   "value": "c4f2b6e782ad53ae6d7e49357bc4b59376817514e6acbf07616b34d9ade1fdd5",
    +   "value": "e981357c06a43edf85bdc005a257253e8e3ea4f22a936284267c1ead247759c9",
      }
      60 |         await nodeA.sendSignedParcel();
      61 |         await wait(4000);
    > 62 |         expect(await nodeA.getBestBlockHash()).toEqual(await nodeB.getBestBlockHash());
         |                                                ^
      63 |       });
      64 |     });
      65 |   });
      at Object.<anonymous> (src/sync.test.ts:62:48)
      at fulfilled (src/sync.test.ts:19:56)
```

**Comment by joojis** [comment]
It seems to have disappeared in the latest version.
