### ISSUE TITLE
Fix the integration test that synchronizing blocks between 2 nodes

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain#662]
Observations:

```
  ● 2 nodes › A-B diverged › nodeA becomes ahead › It should be synced when A-B connected

    Failed: Object {
      "code": -32031,
      "data": "ParcelAlreadyImported",
      "message": "Already Imported",
    }

      84 |
      85 |     describe("nodeA becomes ahead", () => {
    > 86 |       beforeEach(async () => {
         |       ^
      87 |         await nodeA.sendSignedParcel();
      88 |         expect(await nodeA.getBestBlockNumber()).toEqual(await nodeB.getBestBlockNumber() + 1);
      89 |       });

      at Env.beforeEach (node_modules/jest-jasmine2/build/jasmine_async.js:55:24)
      at Suite.describe (src/integration/sync.test.ts:86:7)
      at Suite.describe (src/integration/sync.test.ts:85:5)
```

```
  ● 2 nodes › A-B diverged › nodeA becomes ahead › It should be synced when A-B connected

    CodeChain exited with code 1

      84 |         })
      85 |         .on("close", (code, _signal) => {
    > 86 |           reject(Error(`CodeChain exited with code ${code}`));
         |                  ^
      87 |         });
      88 |
      89 |       const readline = createReadline({ input: this.process!.stderr });

      at ChildProcess.process.on.on (src/helper/spawn.ts:86:18)
```

**Comment by joojis** [comment]
I found that `CodeChain exited with code 1` error can be reproduced(at least in my environment) by the following test:

```
import CodeChain from "../helper/spawn";

let repeat = 50;
while (repeat--) {
test("Start two nodes simultaneously", done => {
    const nodes = [new CodeChain(), new CodeChain()];
    Promise.all(nodes.map(node => node.start()))
        .then(() => Promise.all(nodes.map(node => node.clean())))
        .then(() => done())
        .catch(done.fail);
});
}
```

**Comment by joojis** [comment]
Patch: https://github.com/CodeChain-io/codechain/commit/c7c354b49129ed32291efc59459a7c34800de069

**Comment by joojis** [comment]
The `Already Imported` error disappeared but the other error still exists:

```
    FetchError {
      message: 'request to http://localhost:8125/ failed, reason: connect ECONNREFUSED 127.0.0.1:8125',
      type: 'system',
      errno: 'ECONNREFUSED',
      code: 'ECONNREFUSED' }
```

**Comment by joojis** [comment]
I found the case the initialization is done even if the sync extension isn't initialized.
But I'm not sure that it matters.

log (8085's sync extension wasn't initialized)
```
console.log src/helper/spawn.ts:94
      #4 2018-09-05 14:44:51  main INFO codechain::run_node  Starting client
      #4 2018-09-05 14:44:51  main INFO codechain::run_node  Handshake Listening on 0.0.0.0:3490
      #4 2018-09-05 14:44:51  main INFO discovery  Node runs with unstructured discovery
      #4 2018-09-05 14:44:51  main INFO codechain::rpc  RPC Listening on 127.0.0.1:8085

    console.log src/helper/spawn.ts:94
      #5 2018-09-05 14:44:52  main INFO codechain::run_node  Starting client
      #5 2018-09-05 14:44:52  main INFO codechain::run_node  Handshake Listening on 0.0.0.0:3491
      #5 2018-09-05 14:44:52  main INFO discovery  Node runs with unstructured discovery
      #5 2018-09-05 14:44:52  IO Worker #2 INFO sync  Sync extension initialized
      #5 2018-09-05 14:44:52  main INFO codechain::rpc  RPC Listening on 127.0.0.1:8086
```

error (only 8085 failed)
```
● 2 nodes › nodeA becomes ahead › It should be synced when A-B connected

    FetchError: request to http://localhost:8085/ failed, reason: connect ECONNREFUSED 127.0.0.1:8085

```

**Comment by joojis** [comment]
It seems that the initialization issue is fixed at https://github.com/CodeChain-io/codechain/commit/ccdf607a5da14a290b71ee64260465e107ee5744.


(Line 708 in [the build log](https://travis-ci.org/joojis/codechain/jobs/427586821))
```
console.logsrc/helper/spawn.ts:186
      36 Sync extension initialized: 160 ms
console.logsrc/helper/spawn.ts:179
      36 Initialization complete: 210 ms
console.logsrc/helper/spawn.ts:186
      37 Sync extension initialized: 1638 ms
console.logsrc/helper/spawn.ts:179
      37 Initialization complete: 1701 ms
```

I observed that it took almost 2 seconds to be initialized. But, it won't break the tests.

**Comment by jhs7jhs** [comment]
Currently, there's a problem in `mio::timer` when running in Travis CI.
These are the log files from the test case `2 nodes › A-B connected › It should be synced when nodeA created a block`: nodeA - https://transfer.sh/10Lnh5/rbcmnenvnx.log, nodeB - https://transfer.sh/IstCE/gdb46qgbcm.log
As you can see in the logs, `mio::timer` is not invoked periodically so `on_timeout()` in `sync/src/block/extension` is not called every 1 sec, and its cycle length is about 1 sec ~ 10 sec. So it pass the sync tests rarely.
It can be fixed by upgrade Travis CI, or find another library for more stable timer.
Fortunately, there's a plan to use a shared timer in CodeChain (#349), and it might be possible to fix this problem.
@kseo @sgkim126 @joojis @Kais-DkM

**Comment by Kais-DkM** [comment]
@jhs7jhs  So... is this problem related to "`mio::timer` running on Travis CI"?

**Comment by jhs7jhs** [comment]
Checked that the timers are set properly.

**Comment by Kais-DkM** [comment]
I think there are two possibilities.
1. `mio::timer` is operating correctly, but for somewhat reason `on_timeout` is not triggered at timeout event
2. `on_timeout` is triggered at every timout event, but `mio::timer` itself is not operating correctly, so timeout period is unstable.

Which one is our situation?

**Comment by jhs7jhs** [comment]
@Kais-DkM  2.
Currently, it works well in a local machine. Only matters in Travis. If you want to reproduce, run it in a machine which has few cores.

**Comment by jhs7jhs** [comment]
I separated the timer issue(#759) from here. 
There might be a different issue, so not closing this.
