### ISSUE TITLE
Panicked when the CodeChain gets invalid header

### ISSUE THREAD

**Issue by GNUp** [CodeChain-io/codechain#787]
```
#786789300 2018-10-04 18:55:46  P2P Worker #1 INFO network  New connection from 127.0.0.1:64287(1)
#786789300 2018-10-04 18:55:46  P2P Worker #2 INFO sync  New peer detected #Local V4:6602
#786789300 2018-10-04 18:55:46  P2P Worker #3 INFO sync  Peer #Local V4:6602 status update: total_score: 99999999999999999, best_hash: 0x649f…7bb9
#786789300 2018-10-04 18:55:47  P2P Worker #0 INFO sync  Peer #Local V4:6602 status update: total_score: 999999999999999, best_hash: 0xae5b…e30c

====================

stack backtrace:
   0:     0x7f881d5c5365 - backtrace::backtrace::libunwind::trace::hbcbc5d587d599392
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h1de0bba1bde4ca3b
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x7f881d5c098e - backtrace::capture::Backtrace::new_unresolved::hcd174068355da6d3
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x7f881d5c08ec - backtrace::capture::Backtrace::new::h9bebf8127293178a
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x7f881c6ae4b7 - panic_hook::panic_hook::h4f9be8a1adb26cc9
                        at util/panic_hook/src/lib.rs:53

Thread 'P2P Worker #3' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new

Aborted (core dumped)
```
After the CodeChain gets a sequence of invalid header than it panic.

**Comment by sgkim126** [comment]
@GNUp Do you have a test scenario? How could I reproduce it?

**Comment by GNUp** [comment]
@sgkim126 
You can reproduce this error by below code
```
import { TestHelper } from "../testHelper";

async function sendBlock() {
    const TH = new TestHelper("0.0.0.0", 3485);
    TH.setLog();
    await TH.establish();

    // Genesis block
    const header = TH.soloGenesisBlockHeader();

    // Block 1
    const header1 = TH.soloBlock1(header.hashing());

    // Block 2
    const header2 = TH.soloBlock2(header1.hashing());

    await TH.sendEncodedBlock(
        [
            header.toEncodeObject(),
            header1.toEncodeObject(),
            header2.toEncodeObject()
        ],
        [[], []],
        header2.hashing(),
        header2.getScore()
    );

    await TH.end();
}

sendBlock();
```

**Comment by sgkim126** [comment]
@GNUp I ran the code, but it didn't crash.

**Comment by sgkim126** [comment]
@Kais-DkM What does [pivot](https://github.com/CodeChain-io/codechain/blob/c76ef861a4d4e93057b84425f996e9cd9e1a3b88/sync/src/block/downloader/header.rs#L45) mean?

And why do you rollback pivot if it's not the first response hash?
https://github.com/CodeChain-io/codechain/blob/c76ef861a4d4e93057b84425f996e9cd9e1a3b88/sync/src/block/downloader/header.rs#L135-L138

**Comment by sgkim126** [comment]
FYI, this crash occurs when a peer responses bad hash for the first block. It tries to rollback pivot to parent, but the parent of the genesis block is an invalid block.

**Comment by Kais-DkM** [comment]
Sync extension tracks headers of the best block from "every" peer, and `pivot` means the current target for download.
In short, if peer couldn't answer to the request for `pivot` block, it doesn't have it w.h.p, so we should try tracking it again from the previous block of `pivot`.
Maybe we should stop it reverting when the `pivot` is pointing to genesis.
