### ISSUE TITLE
Subtract overflow in vm

### ISSUE THREAD

**Issue by GNUp** [CodeChain-io/codechain#821]
Fail while integration tests
```

====================

stack backtrace:
   0:     0x7f3b07180695 - backtrace::backtrace::libunwind::trace::h554434f83fd8ade2
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hdeef1f178f364340
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x7f3b0717ad4e - backtrace::capture::Backtrace::new_unresolved::h2123f9609ab9cd57
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x7f3b0717acac - backtrace::capture::Backtrace::new::h17df70671e39b310
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x7f3b061712b1 - panic_hook::panic_hook::h4ad72c185f444842
                        at util/panic_hook/src/lib.rs:53
   4:     0x7f3b06171897 - core::ops::function::Fn::call::h17e79f17b4e32765
                        at libcore/ops/function.rs:78
   5:     0x7f3b07ae3123 - std::panicking::rust_panic_with_hook::h63c14108118b4a75
                        at libstd/panicking.rs:480
   6:     0x7f3b07ae2c89 - std::panicking::continue_panic_fmt::h9ef8711da40a11d7
                        at libstd/panicking.rs:390
   7:     0x7f3b07ae2b85 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x7f3b07b2bd1b - core::panicking::panic_fmt::h5b0d03835cdf4582
                        at libcore/panicking.rs:77
   9:     0x7f3b07b2bc4a - core::panicking::panic::h1429225972c7ea33
                        at libcore/panicking.rs:52
  10:     0x7f3b071ae20e - codechain_vm::executor::execute::h81afea1a71546b36
                        at vm/src/executor.rs:226
  11:     0x7f3b07127a38 - <codechain_state::impls::shard_level::ShardLevelState<B>>::check_and_run_input_script::h9980d634bb674c21
                        at state/src/impls/shard_level.rs:417
  12:     0x7f3b07124784 - <codechain_state::impls::shard_level::ShardLevelState<B>>::transfer_asset::h7b4a05ec7ebd201b
                        at state/src/impls/shard_level.rs:329
  13:     0x7f3b07120e55 - <codechain_state::impls::shard_level::ShardLevelState<B>>::apply_internal::h643e44cfbd3d21bc
                        at state/src/impls/shard_level.rs:167
  14:     0x7f3b0712e537 - <codechain_state::impls::shard_level::ShardLevelState<B> as codechain_state::traits::ShardState<B>>::apply::h06674a2b643631c9
                        at state/src/impls/shard_level.rs:737
  15:     0x7f3b07007d5a - codechain_state::impls::top_level::TopLevelState::apply_transactions_internal::h29d6457e6cad6399
                        at state/src/impls/top_level.rs:569
  16:     0x7f3b07006386 - codechain_state::impls::top_level::TopLevelState::apply_transactions_with_check::he68542d10aadacd3
                        at state/src/impls/top_level.rs:523
  17:     0x7f3b07004598 - codechain_state::impls::top_level::TopLevelState::apply_action::he8524400eb590194
                        at state/src/impls/top_level.rs:446
  18:     0x7f3b070036b5 - codechain_state::impls::top_level::TopLevelState::apply_internal::h4e3cbc08131867d6
                        at state/src/impls/top_level.rs:389
  19:     0x7f3b070025d6 - codechain_state::impls::top_level::TopLevelState::apply::h8a791e663dae8a9b
                        at state/src/impls/top_level.rs:344
  20:     0x7f3b06563382 - codechain_core::block::OpenBlock::push_parcel::hf2f6235cd73161a6
                        at core/src/block.rs:156
  21:     0x7f3b0665e93f - codechain_core::miner::miner::Miner::prepare_block::{{closure}}::hcaa5052bde0a55d4
                        at core/src/miner/miner.rs:399
  22:     0x7f3b063c73f0 - <core::result::Result<T, E>>::and_then::hb89b77550b7411bd
                        at libcore/result.rs:647
  23:     0x7f3b0665d222 - codechain_core::miner::miner::Miner::prepare_block::h4785b3d8ac5b1541
                        at core/src/miner/miner.rs:395
  24:     0x7f3b066614ed - <codechain_core::miner::miner::Miner as codechain_core::miner::MinerService>::update_sealing::h919d03872548911c
                        at core/src/miner/miner.rs:641
  25:     0x7f3b05d0d8db - <codechain_core::miner::miner::Miner as codechain_core::miner::MinerService>::import_own_parcel::h5a08f43962ed1111
                        at /mnt/c/Users/kodebox/Desktop/codechain/core/src/miner/miner.rs:759
  26:     0x7f3b06103b83 - <codechain_rpc::v1::impls::chain::ChainClient<C, M> as codechain_rpc::v1::traits::chain::Chain>::send_signed_parcel::{{closure}}::h09a5709632868585
                        at /mnt/c/Users/kodebox/Desktop/codechain/rpc/src/v1/impls/chain.rs:88
  27:     0x7f3b05e08b15 - <core::result::Result<T, E>>::and_then::h3f2de8ac0dcbc361
                        at libcore/result.rs:647
  28:     0x7f3b06103a5d - <codechain_rpc::v1::impls::chain::ChainClient<C, M> as codechain_rpc::v1::traits::chain::Chain>::send_signed_parcel::hddebfc6df99dc27b
                        at /mnt/c/Users/kodebox/Desktop/codechain/rpc/src/v1/impls/chain.rs:71
  29:     0x7f3b06065bc8 - <for<'r> fn(&'r BASE, A) .> Z as jsonrpc_macros::auto_args::WrapAsync<BASE>>::wrap_rpc::h7424a1f1a27b62f7
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/macros/src/auto_args.rs:382
  30:     0x7f3b05edc0f0 - codechain_rpc::v1::traits::chain::Chain::to_delegate::{{closure}}::hdb0ff71c0f208692
                        at /mnt/c/Users/kodebox/Desktop/codechain/<::jsonrpc_macros::auto_args::build_rpc_trait macros>:56
  31:     0x7f3b05d10d6a - <jsonrpc_macros::delegates::DelegateAsyncMethod<T, F> as jsonrpc_core::calls::RpcMethod<M>>::call::h2709980028f9a8c1
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/macros/src/delegates.rs:25
  32:     0x7f3b05f201b3 - <jsonrpc_core::io::MetaIoHandler<T, S>>::handle_call::{{closure}}::{{closure}}::h7b936fe2cc8297f3
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/core/src/io.rs:225
  33:     0x7f3b05f1923f - <futures::future::lazy::Lazy<F, R>>::get::h3a98e6c940d88a7e
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/lazy.rs:64
  34:     0x7f3b05f19522 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::hb5cc6c4b4f2c99b9
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/lazy.rs:82
  35:     0x7f3b0611858a - <futures::future::chain::Chain<A, B, C>>::poll::h655cf0d8a89d9b93
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/chain.rs:26
  36:     0x7f3b05d65b19 - <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h0a1dc6b6dc21dfb8
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/then.rs:32
  37:     0x7f3b06c691bb - <alloc::boxed::Box<F> as futures::future::Future>::poll::h9cebd6b71795df7f
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/mod.rs:113
  38:     0x7f3b06c78759 - <futures::future::either::Either<A, B> as futures::future::Future>::poll::hbd3a4b12a456e059
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/either.rs:35
  39:     0x7f3b05eef60d - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h167cf6dd8876acb4
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map.rs:30
  40:     0x7f3b06078f49 - <futures::future::either::Either<A, B> as futures::future::Future>::poll::h0c8cbbd45e76ba1a
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/either.rs:35
  41:     0x7f3b06c6917b - <alloc::boxed::Box<F> as futures::future::Future>::poll::h8afe0c2f5794b6f3
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/mod.rs:113
  42:     0x7f3b06c78658 - <futures::future::either::Either<A, B> as futures::future::Future>::poll::h23032f30f8cc492c
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/either.rs:36
  43:     0x7f3b06c5746d - <futures::future::map::Map<A, F> as futures::future::Future>::poll::hbc3387d6a57223ac
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map.rs:30
  44:     0x7f3b05f08811 - <jsonrpc_http_server::handler::RpcHandler<M, S> as futures::future::Future>::poll::hfd99db0e7613a7d5
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/http/src/handler.rs:215
  45:     0x7f3b05f09972 - <jsonrpc_http_server::handler::RpcHandler<M, S> as futures::future::Future>::poll::hfd99db0e7613a7d5
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/http/src/handler.rs:242
  46:     0x7f3b05f09972 - <jsonrpc_http_server::handler::RpcHandler<M, S> as futures::future::Future>::poll::hfd99db0e7613a7d5
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/http/src/handler.rs:242
  47:     0x7f3b05f0e02f - <jsonrpc_http_server::handler::Handler<M, S> as futures::future::Future>::poll::ha66d9fa8f2f051d6
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/http/src/handler.rs:106
  48:     0x7f3b05ef330d - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h5b89b230efc499e5
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map.rs:30
  49:     0x7f3b05d100e0 - <tokio_proto::streaming::pipeline::server::InFlight<F>>::poll::h38a70229349e75a5
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/server.rs:158
  50:     0x7f3b05d0f770 - <tokio_proto::streaming::pipeline::server::Dispatch<S, T, P> as tokio_proto::streaming::pipeline::advanced::Dispatch>::poll::he0dcfea62850ce05
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/server.rs:135
  51:     0x7f3b06056d2c - <tokio_proto::streaming::pipeline::advanced::Pipeline<T>>::write_in_frames::h52afe096b836aa5f
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/advanced.rs:249
  52:     0x7f3b06054f7f - <tokio_proto::streaming::pipeline::advanced::Pipeline<T> as futures::future::Future>::poll::h4f71cfc9439fd452
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-proto-0.1.1/src/streaming/pipeline/advanced.rs:379
  53:     0x7f3b06119f9b - <futures::future::chain::Chain<A, B, C>>::poll::hf86f72cbf0db6859
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/chain.rs:32
  54:     0x7f3b05f81a19 - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h84bfa3bf98771f08
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/and_then.rs:32
  55:     0x7f3b060ca21f - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::h39c834b9f8b78158
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/map_err.rs:30
  56:     0x7f3b077ad5e4 - <alloc::boxed::Box<F> as futures::future::Future>::poll::h84aa11101f738822
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/future/mod.rs:113
  57:     0x7f3b077993c2 - <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}::h4bdbae8c74a2d401
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  58:     0x7f3b077998df - <futures::task_impl::Spawn<T>>::enter::{{closure}}::h1000e039046d5020
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  59:     0x7f3b07782d5b - futures::task_impl::std::set::hddfdec57a89c7ab2
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/std/mod.rs:78
  60:     0x7f3b0779973a - <futures::task_impl::Spawn<T>>::enter::h47be8131180e616c
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:363
  61:     0x7f3b07799349 - <futures::task_impl::Spawn<T>>::poll_future_notify::h49980eb372ac7f66
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.21/src/task_impl/mod.rs:289
  62:     0x7f3b0777ff92 - <tokio::executor::current_thread::scheduler::Scheduled<'a, U>>::tick::h6b13f503da22b373
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/scheduler.rs:352
  63:     0x7f3b0777fe92 - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::{{closure}}::h39c8ab018813785a
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/scheduler.rs:332
  64:     0x7f3b07786662 - <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::{{closure}}::h0a26be6c0763004f
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/mod.rs:688
  65:     0x7f3b07786014 - tokio::executor::current_thread::CurrentRunner::set_spawn::h2112b6f2b70ad7c8
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/mod.rs:720
  66:     0x7f3b07786580 - <tokio::executor::current_thread::Borrow<'a, U>>::enter::{{closure}}::h7cd1991ba8672d97
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/mod.rs:687
  67:     0x7f3b07788240 - <std::thread::local::LocalKey<T>>::try_with::h8f652bbe6becb2d9
                        at libstd/thread/local.rs:294
  68:     0x7f3b07786e96 - <std::thread::local::LocalKey<T>>::with::h54a5f69b607da823
                        at libstd/thread/local.rs:248
  69:     0x7f3b077864cf - <tokio::executor::current_thread::Borrow<'a, U>>::enter::hbe5720bd37db79ba
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/mod.rs:686
  70:     0x7f3b0777fd76 - <tokio::executor::current_thread::scheduler::Scheduler<U>>::tick::hae48c8d11bcfee9f
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/scheduler.rs:332
  71:     0x7f3b0778672d - <tokio::executor::current_thread::Entered<'a, P>>::tick::hfb969e62cc699e27
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/mod.rs:572
  72:     0x7f3b0778686d - <tokio::executor::current_thread::Entered<'a, P>>::turn::h8272a4392323bc79
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.6/src/executor/current_thread/mod.rs:515
  73:     0x7f3b0778b50e - tokio_core::reactor::Core::poll::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hdfdf8c56cf4f32eb
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:298
  74:     0x7f3b0778d2df - <scoped_tls::ScopedKey<T>>::set::hbc88445e5bc59e1d
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155
  75:     0x7f3b0778b9ed - tokio_core::reactor::Core::poll::{{closure}}::{{closure}}::{{closure}}::h32cc79471bb675c5
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:297
  76:     0x7f3b07794809 - tokio_timer::timer::handle::with_default::{{closure}}::hba55bef99676c21f
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.3/src/timer/handle.rs:64
  77:     0x7f3b0778891d - <std::thread::local::LocalKey<T>>::try_with::hbeff928c286730c1
                        at libstd/thread/local.rs:294
  78:     0x7f3b077870ea - <std::thread::local::LocalKey<T>>::with::he1ba0f79aded8dbd
                        at libstd/thread/local.rs:248
  79:     0x7f3b077946ad - tokio_timer::timer::handle::with_default::h0d136251241f2ff1
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.3/src/timer/handle.rs:56
  80:     0x7f3b0778c3f5 - tokio_core::reactor::Core::poll::{{closure}}::{{closure}}::heb5730be43ed3dfc
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:275
  81:     0x7f3b07794d5e - tokio_executor::global::with_default::{{closure}}::hb8ba41feaf822890
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:176
  82:     0x7f3b07787fd9 - <std::thread::local::LocalKey<T>>::try_with::h745aa0c24b740e4d
                        at libstd/thread/local.rs:294
  83:     0x7f3b0778715d - <std::thread::local::LocalKey<T>>::with::hfacb2c6b2ee895c8
                        at libstd/thread/local.rs:248
  84:     0x7f3b07794c0c - tokio_executor::global::with_default::h23a5770812e64721
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.2/src/global.rs:150
  85:     0x7f3b0778c43e - tokio_core::reactor::Core::poll::{{closure}}::hc3db1efc226ec18f
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:274
  86:     0x7f3b07794ab2 - tokio_reactor::with_default::{{closure}}::h9af12060bc32fbcc
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.1/src/lib.rs:207
  87:     0x7f3b077873c9 - <std::thread::local::LocalKey<T>>::try_with::h1172ab8c292c1d95
                        at libstd/thread/local.rs:294
  88:     0x7f3b07786f0d - <std::thread::local::LocalKey<T>>::with::h5ceff7f70be07884
                        at libstd/thread/local.rs:248
  89:     0x7f3b07794920 - tokio_reactor::with_default::hfa1ceff22b7c880e
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.1/src/lib.rs:199
  90:     0x7f3b0778b335 - tokio_core::reactor::Core::poll::h5ba856b1a2dc2eea
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:273
  91:     0x7f3b06cb3482 - tokio_core::reactor::Core::run::h88e0e4d876e8b311
                        at /home/gnu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.17/src/reactor/mod.rs:248
  92:     0x7f3b06cbdfc5 - jsonrpc_server_utils::reactor::RpcEventLoop::with_name::{{closure}}::hc6e9352f73063f1d
                        at /home/gnu/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/811b020/server-utils/src/reactor.rs:104
  93:     0x7f3b06cdd9c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::he3e51d5b08555e7f
                        at libstd/sys_common/backtrace.rs:136
  94:     0x7f3b06cc8484 - std::thread::Builder::spawn::{{closure}}::{{closure}}::he2d5febeaf7636f2
                        at libstd/thread/mod.rs:409
  95:     0x7f3b06cd5aa7 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he9e703a0326b63be
                        at libstd/panic.rs:313
  96:     0x7f3b06cc861f - std::panicking::try::do_call::hd911179842cb267e
                        at libstd/panicking.rs:310
  97:     0x7f3b07af4c59 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  98:     0x7f3b06cc8521 - std::panicking::try::h4273214b9e776832
                        at libstd/panicking.rs:289
  99:     0x7f3b06cd6a97 - std::panic::catch_unwind::hb42dd60c9e02625e
                        at libstd/panic.rs:392
 100:     0x7f3b06cc8298 - std::thread::Builder::spawn::{{closure}}::h99528128cbf6ff7f
                        at libstd/thread/mod.rs:408
 101:     0x7f3b06cc9cdf - <F as alloc::boxed::FnBox<A>>::call_box::h4d7d72e1f161ec1b
                        at liballoc/boxed.rs:672
 102:     0x7f3b07adff6a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h0ff25c6e32ef3241
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h6c5a6b95a9f33338
                        at libstd/sys_common/thread.rs:24
 103:     0x7f3b07acc8b5 - std::sys::unix::thread::Thread::new::thread_start::h5965b51e793f523d
                        at libstd/sys/unix/thread.rs:90
 104:     0x7f3b04e376b9 - start_thread
 105:     0x7f3b0494741c - clone
 106:                0x0 - <unknown>

Thread 'http.worker0' panicked at 'attempt to subtract with overflow', vm/src/executor.rs:226

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new

```

**Comment by sgkim126** [comment]
Currently, a copy instruction crashes when it tries to access an item outside the stack.
I added a test for it ed430926049ea105b78edc035b752dfc8b9f116d and making it skip.

**Comment by sgkim126** [comment]
I think @GNUp can fix it.
Would you fix it and check whether other instructions are safe?
