### ISSUE TITLE
"internal error: entered unreachable code" in `Connection::set_disconnecting`

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#897]
CodeChain crashed while running integration test in local.
It is not easy to reproduce.

Commit hash : 4b9f72cabef6b8c12acab509f117c6c19e157d57

Crash Log

```
====================

stack backtrace:
   0:        0x105237424 - backtrace::backtrace::trace::hde97c2078a40c872
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:        0x10523060c - backtrace::capture::Backtrace::new_unresolved::h018a2194273c4d44
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:        0x10523056e - backtrace::capture::Backtrace::new::h341c2865173f046a
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:        0x103b1dfa7 - panic_hook::panic_hook::h9b42a567c6034ce7
                        at /Users/juhyeong/code/kodebox/codechain/util/panic_hook/src/lib.rs:53
   4:        0x103b1d2f8 - core::ops::function::Fn::call::hdcb7159ae2e618ed
                        at /Users/juhyeong/code/kodebox/codechain/libcore/ops/function.rs:78
   5:        0x105b03038 - std::panicking::rust_panic_with_hook::h67318ff56366ae20
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/panicking.rs:481
   6:        0x1058afaf7 - std::panicking::begin_panic::hccf93344fd721eae
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.2.3/libstd/panicking.rs:411
   7:        0x105374644 - codechain_network::p2p::connection::Connection::set_disconnecting::h347cb115045e30e5
                        at /Users/juhyeong/code/kodebox/codechain/network/src/p2p/connection.rs:477
   8:        0x10531f03a - codechain_network::p2p::connections::Connections::set_disconnecting::h50722655dc8cdc18
                        at /Users/juhyeong/code/kodebox/codechain/network/src/p2p/connections.rs:105
   9:        0x105266c35 - _$LT$codechain_network..p2p..handler..Handler$u20$as$u20$codechain_io..IoHandler$LT$codechain_network..p2p..handler..Message$GT$$GT$::stream_hup::he864dadc1353b134
                        at /Users/juhyeong/code/kodebox/codechain/network/src/p2p/handler.rs:450
  10:        0x1052cb6c1 - codechain_io::worker::Worker::do_work::h9b6d5922cb81b26e
                        at /Users/juhyeong/code/kodebox/codechain/util/io/src/worker.rs:133
  11:        0x1052ccb22 - codechain_io::worker::Worker::work_loop::h2f0d80aa21038f8a
                        at /Users/juhyeong/code/kodebox/codechain/util/io/src/worker.rs:111
  12:        0x1052c8b07 - codechain_io::worker::Worker::new::_$u7b$$u7b$closure$u7d$$u7d$::h2799ecae89324a57
                        at /Users/juhyeong/code/kodebox/codechain/util/io/src/worker.rs:85
  13:        0x105391452 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd2743b734ce49d85
                        at /Users/juhyeong/code/kodebox/codechain/libstd/sys_common/backtrace.rs:136
  14:        0x105280432 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h208505b17e9bc683
                        at /Users/juhyeong/code/kodebox/codechain/libstd/thread/mod.rs:409
  15:        0x1052921d2 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h6d8e02761aba47e1
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panic.rs:313
  16:        0x1053911e1 - std::panicking::try::do_call::h19171eaed007e8ac
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panicking.rs:310
  17:        0x105b0ff9e - __rust_maybe_catch_panic
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libpanic_unwind/lib.rs:103
  18:        0x105391020 - std::panicking::try::hbdcae98693be3774
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panicking.rs:289
  19:        0x105292252 - std::panic::catch_unwind::h552ccdad2fdad674
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panic.rs:392
  20:        0x10527fc73 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::h8fc4b72b3f2427a8
                        at /Users/juhyeong/code/kodebox/codechain/libstd/thread/mod.rs:408
  21:        0x10528054b - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h069121109c5973d9
                        at /Users/juhyeong/code/kodebox/codechain/liballoc/boxed.rs:646
  22:        0x105b01e17 - std::sys_common::thread::start_thread::ha68f94e048f96d59
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/sys_common/thread.rs:24
  23:        0x105aec3d8 - std::sys::unix::thread::Thread::new::thread_start::h57baa5b47ae41e12
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/sys/unix/thread.rs:90
  24:     0x7fff6684133c - _pthread_body
  25:     0x7fff668442a6 - _pthread_start

Thread 'P2P Worker #3' panicked at 'internal error: entered unreachable code', network/src/p2p/connection.rs:477

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new
```

**Comment by majecty** [comment]
This error is caused when set_disconnecting is called while the state is already disconnecting.
But `stream_hup` already check state and it ensures that the state is not `Disconnecting`.
I suppose that `stream_hup` is called twice in two or more threads.

**Comment by majecty** [comment]
There is a log which shows two thread entered `stream_hup`

![2018-11-27 1 46 37](https://user-images.githubusercontent.com/709900/49059165-f105f000-f24a-11e8-934f-9a1da47de33b.png)

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1204 may fix it. Please reopen it if it happens again.
