### ISSUE TITLE
CodeChain panicked with 'Cannot register a disconnecting connection'

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#901]
```
====================

stack backtrace:
   0:        0x10da6a104 - backtrace::backtrace::trace::hde97c2078a40c872
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:        0x10da632ec - backtrace::capture::Backtrace::new_unresolved::h018a2194273c4d44
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:        0x10da6324e - backtrace::capture::Backtrace::new::h341c2865173f046a
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:        0x10c34b1a7 - panic_hook::panic_hook::h9b42a567c6034ce7
                        at /Users/juhyeong/code/kodebox/codechain/util/panic_hook/src/lib.rs:53
   4:        0x10c34a4f8 - core::ops::function::Fn::call::hdcb7159ae2e618ed
                        at /Users/juhyeong/code/kodebox/codechain/libcore/ops/function.rs:78
   5:        0x10e335cf8 - std::panicking::rust_panic_with_hook::h67318ff56366ae20
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/panicking.rs:481
   6:        0x10e33580c - std::panicking::continue_panic_fmt::h2d9dbf1e069d262d
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/panicking.rs:391
   7:        0x10e335760 - std::panicking::begin_panic_fmt::he0631dadb89432ed
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/panicking.rs:346
   8:        0x10dbaacdb - codechain_network::p2p::connection::Connection::register::h7f9e60c5860b29a3
                        at /Users/juhyeong/code/kodebox/codechain/network/src/p2p/connection.rs:528
   9:        0x10db0eda0 - codechain_network::p2p::connections::Connections::register::h0bfb447f74955d57
                        at /Users/juhyeong/code/kodebox/codechain/network/src/p2p/connections.rs:168
  10:        0x10da9a5d5 - _$LT$codechain_network..p2p..handler..Handler$u20$as$u20$codechain_io..IoHandler$LT$codechain_network..p2p..handler..Message$GT$$GT$::register_stream::hb5f1833ece1a5481
                        at /Users/juhyeong/code/kodebox/codechain/network/src/p2p/handler.rs:512
  11:        0x10daf086b - _$LT$codechain_io..service..IoManager$LT$Message$GT$$u20$as$u20$mio..deprecated..handler..Handler$GT$::notify::hf022c165db845f5f
                        at /Users/juhyeong/code/kodebox/codechain/util/io/src/service.rs:360
  12:        0x10db054db - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::notify::hf9a26cb5919b5f52
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:345
  13:        0x10db0424d - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::io_process::h6761a10658ee718f
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:329
  14:        0x10db05e89 - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::run_once::h0f01532c55b83969
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:303
  15:        0x10db04f36 - _$LT$mio..deprecated..event_loop..EventLoop$LT$H$GT$$GT$::run::hc86e6f9f956cae8c
                        at /Users/juhyeong/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.14/src/deprecated/event_loop.rs:264
  16:        0x10daf6089 - _$LT$codechain_io..service..IoManager$LT$Message$GT$$GT$::start::hb1d2bc06051af7a4
                        at /Users/juhyeong/code/kodebox/codechain/util/io/src/service.rs:236
  17:        0x10daf9d70 - _$LT$codechain_io..service..IoService$LT$Message$GT$$GT$::start::_$u7b$$u7b$closure$u7d$$u7d$::hc9cef2bf5d3927e1
                        at /Users/juhyeong/code/kodebox/codechain/util/io/src/service.rs:537
  18:        0x10dbc4064 - std::sys_common::backtrace::__rust_begin_short_backtrace::h06b8e7df64f9e58a
                        at /Users/juhyeong/code/kodebox/codechain/libstd/sys_common/backtrace.rs:136
  19:        0x10dab3164 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h2418f6775acb598c
                        at /Users/juhyeong/code/kodebox/codechain/libstd/thread/mod.rs:409
  20:        0x10dac4e74 - _$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h614c8708a4ea9e9b
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panic.rs:313
  21:        0x10dbc3e24 - std::panicking::try::do_call::h180e466808a8d454
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panicking.rs:310
  22:        0x10e342c5e - __rust_maybe_catch_panic
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libpanic_unwind/lib.rs:103
  23:        0x10dbc3a83 - std::panicking::try::h298fc4f2ad6bf9c3
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panicking.rs:289
  24:        0x10dac5054 - std::panic::catch_unwind::hc8ab986abed055cc
                        at /Users/juhyeong/code/kodebox/codechain/libstd/panic.rs:392
  25:        0x10dab2c4e - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::ha66f8e4cca713060
                        at /Users/juhyeong/code/kodebox/codechain/libstd/thread/mod.rs:408
  26:        0x10dab32b3 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h5e01842dde8b6aee
                        at /Users/juhyeong/code/kodebox/codechain/liballoc/boxed.rs:646
  27:        0x10e334ad7 - std::sys_common::thread::start_thread::ha68f94e048f96d59
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/sys_common/thread.rs:24
  28:        0x10e31f098 - std::sys::unix::thread::Thread::new::thread_start::h57baa5b47ae41e12
                        at /rustc/da5f414c2c0bfe5198934493f04c676e2b23ff2e/src/libstd/sys/unix/thread.rs:90
  29:     0x7fff6684133c - _pthread_body
  30:     0x7fff668442a6 - _pthread_start

Thread '<unnamed>' panicked at 'internal error: entered unreachable code: Cannot register a disconnecting connection', network/src/p2p/connection.rs:528
```

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1204 may fix it. Please reopen it if it happens again.
