### ISSUE TITLE
Panics at update_registration

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/codechain#982]
A node which running Tendermint consensus panicked with below error.
Two of P2P workers panicked at `update_registration` function.

```

====================

stack backtrace:
   0:     0x5568c17977a5 - backtrace::backtrace::libunwind::trace::h4f79420391b53c5e
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h9b33075d5557de4b
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x5568c1791f3e - backtrace::capture::Backtrace::new_unresolved::hec68c6b18a3d0ccb
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x5568c1791e9c - backtrace::capture::Backtrace::new::h52fad09914409242
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x5568c047af51 - panic_hook::panic_hook::he90a460657415dd4
                        at util/panic_hook/src/lib.rs:53
   4:     0x5568c047b537 - core::ops::function::Fn::call::haf5c3a62c69defcf
                        at libcore/ops/function.rs:78
   5:     0x5568c1d9d553 - std::panicking::rust_panic_with_hook::h0e12cb2fc86d00fa
                        at libstd/panicking.rs:481
   6:     0x5568c1d9d0b9 - std::panicking::continue_panic_fmt::h141671b29fe0e27d
                        at libstd/panicking.rs:391
   7:     0x5568c1d9cfb5 - rust_begin_unwind
                        at libstd/panicking.rs:326
   8:     0x5568c1df2e0b - core::panicking::panic_fmt::h429a06507aba9228
                        at libcore/panicking.rs:77
   9:     0x5568c1445323 - core::result::unwrap_failed::h37cc62584b5577fe
                        at libcore/macros.rs:26
  10:     0x5568c144036a - <core::result::Result<T, E>>::unwrap::h8b450c305bf15e95
                        at libcore/result.rs:808
  11:     0x5568c14c1acb - <codechain_io::service::IoContext<Message>>::update_registration::h3d0818a083d2eed6
                        at /code/kodebox/codechain-1/util/io/src/service.rs:155
  12:     0x5568c14293be - <codechain_network::p2p::handler::Handler as codechain_io::IoHandler<codechain_network::p2p::handler::Message>>::stream_writable::{{closure}}::h50bfaed8df87b0a4
                        at network/src/p2p/handler.rs:492
  13:     0x5568c14356e2 - <codechain_finally::Finally<F> as core::ops::drop::Drop>::drop::h7c580c0ae48f53f2
                        at /code/kodebox/codechain-1/util/finally/src/lib.rs:30
  14:     0x5568c14302bd - core::ptr::drop_in_place::hf56d6b9f533d4b3f
                        at libcore/ptr.rs:59
  15:     0x5568c14f5e61 - <codechain_network::p2p::handler::Handler as codechain_io::IoHandler<codechain_network::p2p::handler::Message>>::stream_writable::h1d3111d8ba1d219a
                        at network/src/p2p/handler.rs:495
  16:     0x5568c145c1ec - codechain_io::worker::Worker::do_work::h16d7a951b03e3674
                        at /code/kodebox/codechain-1/util/io/src/worker.rs:128
  17:     0x5568c145efa6 - codechain_io::worker::Worker::work_loop::h118f72cd8dc4169d
                        at /code/kodebox/codechain-1/util/io/src/worker.rs:111
  18:     0x5568c145bb0d - codechain_io::worker::Worker::new::{{closure}}::h639e167213ef7971
                        at /code/kodebox/codechain-1/util/io/src/worker.rs:85
  19:     0x5568c1502dd1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf9d296eb63328325
                        at libstd/sys_common/backtrace.rs:136
  20:     0x5568c14fceb3 - std::thread::Builder::spawn::{{closure}}::{{closure}}::hadef334dc2eb4491
                        at libstd/thread/mod.rs:409
  21:     0x5568c150b1a3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4c02341ba5f06d29
                        at libstd/panic.rs:313
  22:     0x5568c150df99 - std::panicking::try::do_call::he291a46897ab8ddf
                        at libstd/panicking.rs:310
  23:     0x5568c1dc6a89 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  24:     0x5568c150da80 - std::panicking::try::h97aae5a367324163
                        at libstd/panicking.rs:289
  25:     0x5568c150b263 - std::panic::catch_unwind::h181daed8d16c2d81
                        at libstd/panic.rs:392
  26:     0x5568c14fc568 - std::thread::Builder::spawn::{{closure}}::h33c1cb2293bb65af
                        at libstd/thread/mod.rs:408
  27:     0x5568c14fd0dd - <F as alloc::boxed::FnBox<A>>::call_box::hfff9797e3957f3e6
                        at liballoc/boxed.rs:646
  28:     0x5568c1db5dda - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hd022a0500f5eee13
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::hb77935aee02382da
                        at libstd/sys_common/thread.rs:24
  29:     0x5568c1d9dcb5 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75
                        at libstd/sys/unix/thread.rs:90
  30:     0x7ffb2bb596da - start_thread
  31:     0x7ffb2b66a88e - __clone
  32:                0x0 - <unknown>

Thread 'P2P Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: Mio(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") })', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new
```

```

stack backtrace:
   0:     0x5568c17977a5 - backtrace::backtrace::libunwind::trace::h4f79420391b53c5e
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h9b33075d5557de4b
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/backtrace/mod.rs:42
   1:     0x5568c1791f3e - backtrace::capture::Backtrace::new_unresolved::hec68c6b18a3d0ccb
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:88
   2:     0x5568c1791e9c - backtrace::capture::Backtrace::new::h52fad09914409242
                        at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.7/src/capture.rs:63
   3:     0x5568c047af51 - panic_hook::panic_hook::he90a460657415dd4
                        at util/panic_hook/src/lib.rs:53
   4:     0x5568c047b537 - core::ops::function::Fn::call::haf5c3a62c69defcf
                        at libcore/ops/function.rs:78
   5:     0x5568c1d9d553 - std::panicking::rust_panic_with_hook::h0e12cb2fc86d00fa
                        at libstd/panicking.rs:481
   6:     0x5568c1d9d0b9 - std::panicking::continue_panic_fmt::h141671b29fe0e27d
                        at libstd/panicking.rs:391
   7:     0x5568c1d9cfb5 - rust_begin_unwind
                        at libstd/panicking.rs:326
   8:     0x5568c1df2e0b - core::panicking::panic_fmt::h429a06507aba9228
                        at libcore/panicking.rs:77
   9:     0x5568c1445323 - core::result::unwrap_failed::h37cc62584b5577fe
                        at libcore/macros.rs:26
  10:     0x5568c144036a - <core::result::Result<T, E>>::unwrap::h8b450c305bf15e95
                        at libcore/result.rs:808
  11:     0x5568c14c1acb - <codechain_io::service::IoContext<Message>>::update_registration::h3d0818a083d2eed6
                        at /code/kodebox/codechain-1/util/io/src/service.rs:155
  12:     0x5568c14293be - <codechain_network::p2p::handler::Handler as codechain_io::IoHandler<codechain_network::p2p::handler::Message>>::stream_writable::{{closure}}::h50bfaed8df87b0a4
                        at network/src/p2p/handler.rs:492
  13:     0x5568c14356e2 - <codechain_finally::Finally<F> as core::ops::drop::Drop>::drop::h7c580c0ae48f53f2
                        at /code/kodebox/codechain-1/util/finally/src/lib.rs:30
  14:     0x5568c14302bd - core::ptr::drop_in_place::hf56d6b9f533d4b3f
                        at libcore/ptr.rs:59
  15:     0x5568c14f5e61 - <codechain_network::p2p::handler::Handler as codechain_io::IoHandler<codechain_network::p2p::handler::Message>>::stream_writable::h1d3111d8ba1d219a
                        at network/src/p2p/handler.rs:495
  16:     0x5568c145c1ec - codechain_io::worker::Worker::do_work::h16d7a951b03e3674
                        at /code/kodebox/codechain-1/util/io/src/worker.rs:128
  17:     0x5568c145efa6 - codechain_io::worker::Worker::work_loop::h118f72cd8dc4169d
                        at /code/kodebox/codechain-1/util/io/src/worker.rs:111
  18:     0x5568c145bb0d - codechain_io::worker::Worker::new::{{closure}}::h639e167213ef7971
                        at /code/kodebox/codechain-1/util/io/src/worker.rs:85
  19:     0x5568c1502dd1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf9d296eb63328325
                        at libstd/sys_common/backtrace.rs:136
  20:     0x5568c14fceb3 - std::thread::Builder::spawn::{{closure}}::{{closure}}::hadef334dc2eb4491
                        at libstd/thread/mod.rs:409
  21:     0x5568c150b1a3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4c02341ba5f06d29
                        at libstd/panic.rs:313
  22:     0x5568c150df99 - std::panicking::try::do_call::he291a46897ab8ddf
                        at libstd/panicking.rs:310
  23:     0x5568c1dc6a89 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  24:     0x5568c150da80 - std::panicking::try::h97aae5a367324163
                        at libstd/panicking.rs:289
  25:     0x5568c150b263 - std::panic::catch_unwind::h181daed8d16c2d81
                        at libstd/panic.rs:392
  26:     0x5568c14fc568 - std::thread::Builder::spawn::{{closure}}::h33c1cb2293bb65af
                        at libstd/thread/mod.rs:408
  27:     0x5568c14fd0dd - <F as alloc::boxed::FnBox<A>>::call_box::hfff9797e3957f3e6
                        at liballoc/boxed.rs:646
  28:     0x5568c1db5dda - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$RP$$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::hd022a0500f5eee13
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::hb77935aee02382da
                        at libstd/sys_common/thread.rs:24
  29:     0x5568c1d9dcb5 - std::sys::unix::thread::Thread::new::thread_start::hd61f7429b3de1d75
                        at libstd/sys/unix/thread.rs:90
  30:     0x7ffb2bb596da - start_thread
  31:     0x7ffb2b66a88e - __clone
  32:                0x0 - <unknown>

Thread 'P2P Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: Mio(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") })', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/CodeChain-io/codechain/issues/new
```

**Comment by majecty** [comment]
2019-02-02 10:25:23 UTC corgi-us-west-1-2

**Comment by sgkim126** [comment]
I added a patch to log more information b744020d92128a20a211bdbad400d98b9818c0f0

**Comment by sgkim126** [comment]
https://github.com/CodeChain-io/codechain/pull/1204 may fix it. Please reopen it if it happens again.
